//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbirProjectCars.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_Abir_GarageDBEntities : DbContext
    {
        public MVC_Abir_GarageDBEntities()
            : base("name=MVC_Abir_GarageDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Garage> Garage { get; set; }
        public virtual DbSet<GaragePermissions> GaragePermissions { get; set; }
        public virtual DbSet<GarageVisits> GarageVisits { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
    }
}
